[
  {
    "device": "Galaxy S24",
    "status": "failure",
    "stdout": "============================= test session starts =============================\nplatform win32 -- Python 3.13.2, pytest-8.3.5, pluggy-1.5.0\nrootdir: C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\Home\nplugins: base-url-2.1.0, html-4.1.1, json-0.4.0, json-report-1.5.0, metadata-3.1.1, ordering-0.6, playwright-0.7.0\ncollected 0 items / 1 error\n\n=================================== ERRORS ====================================\n_________________ ERROR collecting tests/home/test_landing.py _________________\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\python.py:493: in importtestmodule\n    mod = import_path(\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\pathlib.py:587: in import_path\n    importlib.import_module(module_name)\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\importlib\\__init__.py:88: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n<frozen importlib._bootstrap>:1387: in _gcd_import\n    ???\n<frozen importlib._bootstrap>:1360: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:1331: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:935: in _load_unlocked\n    ???\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\assertion\\rewrite.py:176: in exec_module\n    source_stat, co = _rewrite_test(fn, self.config)\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\assertion\\rewrite.py:356: in _rewrite_test\n    tree = ast.parse(source, filename=strfn)\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\ast.py:54: in parse\n    return compile(source, filename, mode, flags,\nE     File \"C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\Home\\tests\\home\\test_landing.py\", line 35\nE       expect(page).to_have_url(URLS[\"home_policy\"]))\nE                                                    ^\nE   SyntaxError: unmatched ')'\n=========================== short test summary info ===========================\nERROR tests/home/test_landing.py\n!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!\n============================== 1 error in 0.15s ===============================\n",
    "stderr": ""
  },
  {
    "device": "Galaxy A15",
    "status": "failure",
    "stdout": "============================= test session starts =============================\nplatform win32 -- Python 3.13.2, pytest-8.3.5, pluggy-1.5.0\nrootdir: C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\Home\nplugins: base-url-2.1.0, html-4.1.1, json-0.4.0, json-report-1.5.0, metadata-3.1.1, ordering-0.6, playwright-0.7.0\ncollected 0 items / 1 error\n\n=================================== ERRORS ====================================\n_________________ ERROR collecting tests/home/test_landing.py _________________\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\python.py:493: in importtestmodule\n    mod = import_path(\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\pathlib.py:587: in import_path\n    importlib.import_module(module_name)\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\importlib\\__init__.py:88: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n<frozen importlib._bootstrap>:1387: in _gcd_import\n    ???\n<frozen importlib._bootstrap>:1360: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:1331: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:935: in _load_unlocked\n    ???\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\assertion\\rewrite.py:176: in exec_module\n    source_stat, co = _rewrite_test(fn, self.config)\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\assertion\\rewrite.py:356: in _rewrite_test\n    tree = ast.parse(source, filename=strfn)\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\ast.py:54: in parse\n    return compile(source, filename, mode, flags,\nE     File \"C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\Home\\tests\\home\\test_landing.py\", line 35\nE       expect(page).to_have_url(URLS[\"home_policy\"]))\nE                                                    ^\nE   SyntaxError: unmatched ')'\n=========================== short test summary info ===========================\nERROR tests/home/test_landing.py\n!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!\n============================== 1 error in 0.14s ===============================\n",
    "stderr": ""
  },
  {
    "device": "iPhone 14 Pro Max",
    "status": "failure",
    "stdout": "============================= test session starts =============================\nplatform win32 -- Python 3.13.2, pytest-8.3.5, pluggy-1.5.0\nrootdir: C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\Home\nplugins: base-url-2.1.0, html-4.1.1, json-0.4.0, json-report-1.5.0, metadata-3.1.1, ordering-0.6, playwright-0.7.0\ncollected 0 items / 1 error\n\n=================================== ERRORS ====================================\n_________________ ERROR collecting tests/home/test_landing.py _________________\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\python.py:493: in importtestmodule\n    mod = import_path(\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\pathlib.py:587: in import_path\n    importlib.import_module(module_name)\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\importlib\\__init__.py:88: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n<frozen importlib._bootstrap>:1387: in _gcd_import\n    ???\n<frozen importlib._bootstrap>:1360: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:1331: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:935: in _load_unlocked\n    ???\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\assertion\\rewrite.py:176: in exec_module\n    source_stat, co = _rewrite_test(fn, self.config)\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\assertion\\rewrite.py:356: in _rewrite_test\n    tree = ast.parse(source, filename=strfn)\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\ast.py:54: in parse\n    return compile(source, filename, mode, flags,\nE     File \"C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\Home\\tests\\home\\test_landing.py\", line 35\nE       expect(page).to_have_url(URLS[\"home_policy\"]))\nE                                                    ^\nE   SyntaxError: unmatched ')'\n=========================== short test summary info ===========================\nERROR tests/home/test_landing.py\n!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!\n============================== 1 error in 0.15s ===============================\n",
    "stderr": ""
  },
  {
    "device": "iPhone 15",
    "status": "failure",
    "stdout": "============================= test session starts =============================\nplatform win32 -- Python 3.13.2, pytest-8.3.5, pluggy-1.5.0\nrootdir: C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\Home\nplugins: base-url-2.1.0, html-4.1.1, json-0.4.0, json-report-1.5.0, metadata-3.1.1, ordering-0.6, playwright-0.7.0\ncollected 0 items / 1 error\n\n=================================== ERRORS ====================================\n_________________ ERROR collecting tests/home/test_landing.py _________________\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\python.py:493: in importtestmodule\n    mod = import_path(\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\pathlib.py:587: in import_path\n    importlib.import_module(module_name)\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\importlib\\__init__.py:88: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n<frozen importlib._bootstrap>:1387: in _gcd_import\n    ???\n<frozen importlib._bootstrap>:1360: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:1331: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:935: in _load_unlocked\n    ???\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\assertion\\rewrite.py:176: in exec_module\n    source_stat, co = _rewrite_test(fn, self.config)\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\assertion\\rewrite.py:356: in _rewrite_test\n    tree = ast.parse(source, filename=strfn)\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\ast.py:54: in parse\n    return compile(source, filename, mode, flags,\nE     File \"C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\Home\\tests\\home\\test_landing.py\", line 35\nE       expect(page).to_have_url(URLS[\"home_policy\"]))\nE                                                    ^\nE   SyntaxError: unmatched ')'\n=========================== short test summary info ===========================\nERROR tests/home/test_landing.py\n!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!\n============================== 1 error in 0.19s ===============================\n",
    "stderr": ""
  }
]